### ISSUE TITLE
Crypting RAT server using XORFile

### ISSUE THREAD

**Issue by ghost** [leirn/XORFile#1]
hi leirn,how i can use your source code to encrypt my nanocore rat server

**Comment by leirn** [comment]
Hi.
I am not sure to understand what you want to do, knowing nothing about nanocore rat servers.
If you want to use the "algorithme" part of the code, everything is in xor.c. The same fonction is used to crypy and uncrypt.
I hope this Will help you.

**Comment by ghost** [comment]
thanks

2016-08-10 6:42 GMT+01:00 leirn notifications@github.com:
